version: '3.7'
services:
  iris:
    init: true
    #image: containers.intersystems.com/intersystems/irishealth-aa-community:2020.3.0AA.331.0
    #Downloaded from wrc:
    image: containers.intersystems.com/intersystems/irishealth:2020.3.0AA.331.0
    restart: always
    environment:
      - ISC_DATA_DIRECTORY=/dur/config
      - ISC_CPF_MERGE_FILE=/irisdev/app/iris.cpf
    ports: 
      - "62773:52773"
      - "63773:53773"
    volumes:
      - ./:/irisdev/app
      - config:/dur
    #password has is in cpf, instead
    #command: --password-file /irisdev/app/password.txt --key /irisdev/app/irislicense/iris.key
    command:  --key /irisdev/app/irislicense/iris.key
volumes:
  config: ~